FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install pytest

COPY ./app ./app
COPY ./tests ./tests
COPY data/ethereum_txs.csv /app/data/ethereum_txs.csv

CMD ["pytest", "/app/tests"]
